package projet_abc;

import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.event.*;
import java.awt.*;
import java.text.*;
import java.awt.print.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;


/**
 *
 * @author sara
 */
public class Historique_frame extends javax.swing.JFrame {

   

   

    

    Connection conn =null;
    
    ResultSet rs=null;
    
    PreparedStatement pst= null;
    static private String server_name;
   static private String data_base_name;
   static  private String user_name;
   static  private String password;
    
    public Historique_frame(String sn, String db , String un, String pa) {
        server_name=sn;
        data_base_name=db;
        user_name=un;
        password=pa;
        initComponents();
        conn=TableEmployee.ConnecrDb(server_name,data_base_name,user_name,password);
        update_Table ();
        
             
    }
     /**
     *
     */
  
        
       
    
     public void close(){

WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);


}
 

    private void update_Table (){
    
    String sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches Order by historique_date desc  ";
      try{
     pst= conn.prepareStatement(sql);
     rs=pst.executeQuery();
     table_resultat.setModel(DbUtils.resultSetToTableModel(rs));
      }
      
      catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       
      }
      finally{
        try{
        
       
        pst.close();
        
        
        }catch(Exception e){
            
      JOptionPane.showMessageDialog(null,e);
        }
        
        
        
        }
         
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        text_recherche = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        projet_nom = new javax.swing.JTextField();
        operation = new javax.swing.JTextField();
        titre_tache = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        id_historique = new javax.swing.JTextField();
        historique_date = new javax.swing.JTextField();
        date_debut_tache = new javax.swing.JTextField();
        date_fin_tache = new javax.swing.JTextField();
        duree_tache = new javax.swing.JTextField();
        person_nom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        person_email = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        chef_projet_email = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        chef_projet_nom = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        boutton_sauvgarder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resultat = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        boutton_sauvgarder1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historique");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getToolkit().getImage(getClass().getResource("/history_icon.gif")));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche : Par nom , par email ...etc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_recherche.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        text_recherche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_rechercheActionPerformed(evt);
            }
        });
        text_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_rechercheKeyReleased(evt);
            }
        });
        jPanel3.add(text_recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Opération :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "creation", "mise a jour", "suppression", "complete", "Alerte" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 30));

        jButton1.setBackground(new java.awt.Color(153, 180, 209));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Rechercher");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        projet_nom.setEditable(false);
        projet_nom.setBackground(new java.awt.Color(255, 255, 255));
        projet_nom.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        projet_nom.setBorder(null);
        projet_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projet_nomActionPerformed(evt);
            }
        });
        jPanel1.add(projet_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 230, 20));

        operation.setEditable(false);
        operation.setBackground(new java.awt.Color(255, 255, 255));
        operation.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        operation.setBorder(null);
        operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationActionPerformed(evt);
            }
        });
        jPanel1.add(operation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, 20));

        titre_tache.setEditable(false);
        titre_tache.setBackground(new java.awt.Color(255, 255, 255));
        titre_tache.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        titre_tache.setBorder(null);
        jPanel1.add(titre_tache, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("L'opération :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 20));

        id_historique.setEditable(false);
        id_historique.setBackground(new java.awt.Color(255, 255, 255));
        id_historique.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        id_historique.setForeground(new java.awt.Color(204, 0, 0));
        id_historique.setBorder(null);
        id_historique.setFocusable(false);
        jPanel1.add(id_historique, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 230, 20));

        historique_date.setEditable(false);
        historique_date.setBackground(new java.awt.Color(255, 255, 255));
        historique_date.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        historique_date.setBorder(null);
        jPanel1.add(historique_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 230, 20));

        date_debut_tache.setEditable(false);
        date_debut_tache.setBackground(new java.awt.Color(255, 255, 255));
        date_debut_tache.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        date_debut_tache.setBorder(null);
        jPanel1.add(date_debut_tache, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 230, 20));

        date_fin_tache.setEditable(false);
        date_fin_tache.setBackground(new java.awt.Color(255, 255, 255));
        date_fin_tache.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        date_fin_tache.setBorder(null);
        jPanel1.add(date_fin_tache, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 230, 20));

        duree_tache.setEditable(false);
        duree_tache.setBackground(new java.awt.Color(255, 255, 255));
        duree_tache.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        duree_tache.setBorder(null);
        jPanel1.add(duree_tache, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 230, 20));

        person_nom.setEditable(false);
        person_nom.setBackground(new java.awt.Color(255, 255, 255));
        person_nom.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        person_nom.setForeground(new java.awt.Color(204, 0, 0));
        person_nom.setBorder(null);
        jPanel1.add(person_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Clé historique :");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Le nom du projet :");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Le début du tâche :");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Date :");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("La fin du tâche :");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 130, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("La durée du tâche :");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 130, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Tâche assigné a :");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Le nom du tache :");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 20));

        person_email.setEditable(false);
        person_email.setBackground(new java.awt.Color(255, 255, 255));
        person_email.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        person_email.setForeground(new java.awt.Color(204, 0, 0));
        person_email.setBorder(null);
        jPanel1.add(person_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 230, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Assigné a (email) :");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 130, 20));

        chef_projet_email.setEditable(false);
        chef_projet_email.setBackground(new java.awt.Color(255, 255, 255));
        chef_projet_email.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        chef_projet_email.setBorder(null);
        jPanel1.add(chef_projet_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 230, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Chef du projet (email)");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 140, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Chef du projet");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 130, 20));

        chef_projet_nom.setEditable(false);
        chef_projet_nom.setBackground(new java.awt.Color(255, 255, 255));
        chef_projet_nom.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        chef_projet_nom.setBorder(null);
        jPanel1.add(chef_projet_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 230, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 10, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 780, 140));

        boutton_sauvgarder.setBackground(java.awt.SystemColor.activeCaption);
        boutton_sauvgarder.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        boutton_sauvgarder.setForeground(new java.awt.Color(255, 255, 255));
        boutton_sauvgarder.setText("Aide ?");
        boutton_sauvgarder.setBorder(null);
        boutton_sauvgarder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutton_sauvgarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_sauvgarderActionPerformed(evt);
            }
        });
        getContentPane().add(boutton_sauvgarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 110, 48));

        table_resultat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_resultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_resultat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_resultatMouseClicked(evt);
            }
        });
        table_resultat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_resultatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_resultatKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_resultat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 780, 220));

        jTextField1.setBackground(new java.awt.Color(0, 0, 51));
        jTextField1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Détails");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 30));

        jScrollPane2.setBackground(new java.awt.Color(153, 204, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 204, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(2);
        jTextArea1.setText("Cette page sert a affichier l'historique de tous les opérations effectué par l'application .\n\t- Vous pouvez filtrer les resultats en utilisant panneau de recherche\n\t- Utiliser les flèches après la sélection par souris pour afficher les détails ");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        boutton_sauvgarder1.setBackground(java.awt.SystemColor.activeCaption);
        boutton_sauvgarder1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        boutton_sauvgarder1.setForeground(new java.awt.Color(255, 255, 255));
        boutton_sauvgarder1.setText("Sauvgarder");
        boutton_sauvgarder1.setBorder(null);
        boutton_sauvgarder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutton_sauvgarder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutton_sauvgarder1ActionPerformed(evt);
            }
        });
        getContentPane().add(boutton_sauvgarder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 110, 48));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutton_sauvgarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_sauvgarderActionPerformed
       try {
            java.awt.Desktop.getDesktop().open(new File("setting/index2.html"));
            
        } catch (IOException ex) {
            Logger.getLogger(Historique_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boutton_sauvgarderActionPerformed

    private void boutton_sauvgarder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutton_sauvgarder1ActionPerformed
         MessageFormat header= new MessageFormat(" liste ");
        MessageFormat footer= new MessageFormat(" Page{0,number,integer}");

        try{

            table_resultat.print(JTable.PrintMode.NORMAL, header, footer);

        }catch(java.awt.print.PrinterException e){
            System.err.format("impossible de sauvgarder %s%n ", e.getMessage());

        }
    }//GEN-LAST:event_boutton_sauvgarder1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String  sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches Order by historique_date desc";
        if("".equals(text_recherche.getText()))
        {
            if("Tous".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches Order by historique_date desc";
            }

            else if("creation".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches where operations='creation' Order by historique_date desc";
            }

            else if("mise a jour".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches where operations='mise a jour' Order by historique_date desc";
            }

            else if("suppression".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches where operations='suppression' Order by historique_date desc";
            }

            else if("complete".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches where operations='complete' Order by historique_date desc";
            }

            else if("Alerte".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom From historique_taches where operations='Alerte' Order by historique_date desc";
            }

        }
        else
        {
            String word=text_recherche.getText().toLowerCase();
            if("Tous".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom "
                + "From historique_taches WHERE LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"'  Order by historique_date desc";
            }

            else if("creation".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom "
                + "From historique_taches where operations='creation' AND ( LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"' )  Order by historique_date desc";
            }

            else if("mise a jour".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom"
                + " From historique_taches where operations='mise a jour'  AND ( LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"' )  Order by historique_date desc";
            }

            else if("suppression".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom "
                + "From historique_taches where operations='suppression'  AND ( LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"' )  Order by historique_date desc";
            }

            else if("complete".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom "
                + "From historique_taches where operations='complete'  AND ( LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"' )  Order by historique_date desc";
            }

            else if("Alerte".equals((String)jComboBox1.getSelectedItem()))
            {
                sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,person_email,person_nom "
                + "From historique_taches where operations='Alerte'  AND ( LOWER(projet_nom)='"+word+"' OR LOWER(titre_tache)='"+word+"' OR LOWER(person_email)='"+word+"' OR LOWER(person_nom)='"+word+"' ) Order by historique_date desc ";
            }

        }

        try{
            pst= conn.prepareStatement(sql);
            rs=pst.executeQuery();

            table_resultat.setModel(DbUtils.resultSetToTableModel(rs));
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
        finally{
            try{

                pst.close();

            }catch(Exception e){

                JOptionPane.showMessageDialog(null,e);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_rechercheKeyReleased
        try{
            String sql="select * From historique_taches where chef_projet_nom=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,text_recherche.getText());
            rs=pst.executeQuery();

            if(rs.next()){

                String add1=rs.getString("id_historique");
                id_historique.setText(add1);
                String add2=rs.getString("historique_date");
                historique_date.setText(add2);
                String add3=rs.getString("operations");
                operation.setText(add3);
                String add4=rs.getString("projet_nom");
                projet_nom.setText(add4);
                String add5=rs.getString("titre_tache");
                titre_tache.setText(add5);
                String add6=rs.getString("date_debut_tache");
                date_debut_tache.setText(add6);
                String add7=rs.getString("date_fin_tache");
                date_fin_tache.setText(add7);
                String add8=rs.getString("duree_tache");
                duree_tache.setText(add8);
                String add9=rs.getString("person_email");
                person_email.setText(add9);
                String add10=rs.getString("person_nom");
                person_nom.setText(add10);
                String add11=rs.getString("chef_projet_email");
                chef_projet_email.setText(add11);
                String add12=rs.getString("chef_projet_nom");
                chef_projet_nom.setText(add12);

            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_text_rechercheKeyReleased

    private void text_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_rechercheActionPerformed

    private void table_resultatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_resultatKeyReleased

        try{
            int row =table_resultat.getSelectedRow();
            String Table_Click=(table_resultat.getModel().getValueAt(row, 0).toString());
            String sql="select  id_historique, historique_date , operations  , projet_nom ,titre_tache,date_debut_tache,date_fin_tache,duree_tache,person_email,person_nom,chef_projet_email,chef_projet_nom From historique_taches where id_historique='"+Table_Click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("id_historique");
                id_historique.setText(add1);

                String add2=rs.getString("historique_date");
                historique_date.setText(add2);

                String add3=rs.getString("operations");
                operation.setText(add3);

                String add4=rs.getString("projet_nom");
                projet_nom.setText(add4);

                String add5=rs.getString("titre_tache");
                titre_tache.setText(add5);
                String add6=rs.getString("date_debut_tache");
                date_debut_tache.setText(add6);
                String add7=rs.getString("date_fin_tache");
                date_fin_tache.setText(add7);
                String add8=rs.getString("duree_tache");
                duree_tache.setText(add8);
                String add9=rs.getString("person_email");
                person_nom.setText(add9);
                String add10=rs.getString("person_nom");
                person_nom.setText(add10);

                String add11=rs.getString("chef_projet_email");
                chef_projet_email.setText(add11);
                String add12=rs.getString("chef_projet_nom");
                chef_projet_nom.setText(add12);

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(null,e);

        }
        finally{
            try{

                pst.close();

            }catch(Exception e){

                JOptionPane.showMessageDialog(null,e);
            }

        }
    }//GEN-LAST:event_table_resultatKeyReleased

    private void table_resultatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_resultatKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){

            try{
                int row =table_resultat.getSelectedRow();
                String Table_Click=(table_resultat.getValueAt(row, 0).toString());
                String sql="select id_historique, historique_date , operations  , projet_nom ,titre_tache,date_debut_tache,date_fin_tache,duree_tache,person_email,person_nom,chef_projet_email,chef_projet_nom From historique_taches where id_historique='"+Table_Click+"'";
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    String add1=rs.getString("id_historique");
                    id_historique.setText(add1);

                    String add2=rs.getString("historique_date");
                    historique_date.setText(add2);

                    String add3=rs.getString("operations");
                    operation.setText(add3);

                    String add4=rs.getString("projet_nom");
                    projet_nom.setText(add4);
                    String add5=rs.getString("titre_tache");
                    titre_tache.setText(add5);

                    String add6=rs.getString("date_debut_tache");
                    date_debut_tache.setText(add6);

                    String add7=rs.getString("date_fin_tache");
                    date_fin_tache.setText(add7);

                    String add8=rs.getString("duree_tache");
                    duree_tache.setText(add8);

                    String add9=rs.getString("person_email");
                    person_email.setText(add9);

                    String add10=rs.getString("person_nom");
                    person_nom.setText(add10);
                    String add11=rs.getString("chef_projet_email");
                    chef_projet_email.setText(add11);
                    String add12=rs.getString("chef_projet_nom");
                    chef_projet_nom.setText(add12);

                }

            }catch(Exception e){

                JOptionPane.showMessageDialog(null,e);

            }

        }
    }//GEN-LAST:event_table_resultatKeyPressed

    private void table_resultatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_resultatMouseClicked

    }//GEN-LAST:event_table_resultatMouseClicked

    private void operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operationActionPerformed

    private void projet_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projet_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projet_nomActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historique_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historique_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historique_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historique_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Historique_frame(server_name,data_base_name,user_name,password).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutton_sauvgarder;
    private javax.swing.JButton boutton_sauvgarder1;
    private javax.swing.JTextField chef_projet_email;
    private javax.swing.JTextField chef_projet_nom;
    private javax.swing.JTextField date_debut_tache;
    private javax.swing.JTextField date_fin_tache;
    private javax.swing.JTextField duree_tache;
    private javax.swing.JTextField historique_date;
    private javax.swing.JTextField id_historique;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField operation;
    private javax.swing.JTextField person_email;
    private javax.swing.JTextField person_nom;
    private javax.swing.JTextField projet_nom;
    private javax.swing.JTable table_resultat;
    private javax.swing.JTextField text_recherche;
    private javax.swing.JTextField titre_tache;
    // End of variables declaration//GEN-END:variables
}
